stages:
  # prepare:
  #   cmd: python src/prepare.py
  #   deps:
  #   - ../data/train/video
  #   params:
  #   - generate.dancers
  #   - generate.tags
  #   - generate.random_state
  #   - generate.test_size
  #   - generate.validation_split
  #   - generate.look_back
  #   outs:
  #   - ../data/train/prepared
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    params:
    - train.dancers
    - train.tags
    - train.random_state
    - train.test_size
    - train.validation_split
    - train.look_back
    - train.normalize_body
    - train.hip_correction
    - train.batch_size
    - train.epochs
    - train.lstm_layer
    - train.mdn_layer
    outs:
    - ../data/models
    metrics:
    - ../data/metrics/deep-dance-scores.json:
        cache: false
    plots:
    - ../data/metrics/deep-dance-loss.json:
        cache: false
  generate:
    cmd: python src/generate.py
    deps:
    - src/generate.py
    - ../data/models
    params:
    - generate.dancers
    - generate.tags
    - generate.random_state
    - generate.test_size
    - generate.validation_split
    - generate.look_back
    - generate.normalize_body
    - generate.hip_correction

    - generate.seed
    - generate.steps_limit
    outs:
    - ../data/generated

