prepare:
  look_back: 10
  split: 0.05
  random_state: 42
  dancers: 'maria'
  tags: 'impro'

train:
  epochs: 1
  batch_size: 128
  look_back: 10
  lstm_layer: 32
  mdn_layer: 3
  custom_loss: True
  random_state: 42
  dancers: 'maria'
  tags: 'impro'

generate:
  look_back: 10
  random_state: 42
  seed: 1500
  steps_limit: 1500
  custom_loss: True