prepare:
  dancers: all
  tags: impro
  random_state: 42
  test_size: 0.05
  validation_split: 0.1
  look_back: 10

train:
  dancers: tinyeung
  tags: walking
  random_state: 42
  test_size: 0.05
  validation_split: 0.1
  look_back: 10
  normalize_body: true
  hip_correction: false
  epochs: 3
  batch_size: 64
  lstm_layer: 64
  mdn_layer: 3

generate:
  dancers: tinyeung
  tags: walking
  random_state: 42
  test_size: 0.05
  validation_split: 0.1
  look_back: 10
  normalize_body: true
  hip_correction: false
  seed: 0
  steps_limit: 1500


