prepare:
  look_back: 10
  split: 0.05
  random_state: 42
  dancers: all
  tags: impro

train:
  epochs: 10
  batch_size: 32
  look_back: 70
  lstm_layer: 128
  mdn_layer: 3
  custom_loss: true
  random_state: 42
  dancers: all
  tags: impro
  test_size: 0.05
  validation_split: 0.3

generate:
  look_back: 70
  random_state: 42
  seed: 1500
  steps_limit: 1500
  custom_loss: true
  dancers: all
  tags: impro
  test_size: 0.05
  validation_split: 0.3
