prepare:
  look_back: 10
  split: 0.05
  random_state: 42

train:
  data: all
  epochs: 10
  batch_size: 128
  look_back: 10
  lstm_layer: 64
  mdn_layer: 3
  custom_loss: true
  random_state: 42

generate:
  look_back: 10
  random_state: 42
  seed: 1500
  steps_limit: 1500
  custom_loss: true
