prepare:
  dancers: all
  tags: impro
  random_state: 42
  test_size: 0.05
  validation_split: 0.1
  look_back: 10

# TODO: Move and merge dataset
# train and generate params into 
# prepare stage
train:
  dancers: maria,raymond
  tags: impro
  random_state: 42
  test_size: 0.05
  validation_split: 0.9
  look_back: 10
  normalize_body: true
  hip_correction: false
  kinetic: true
  epochs: 10
  batch_size: 64
  lstm_layer: 32
  mdn_layer: 3

generate:
  dancers: maria,raymond
  tags: impro
  random_state: 42
  test_size: 0.05
  validation_split: 0.9
  look_back: 10
  normalize_body: true
  hip_correction: false
  kinetic: true
  seed: 1500
  steps_limit: 1500


